sudo: required

services:
- docker

env:
  matrix:
  - BUILDFOLDER=rokku-dev-apache-ranger
  - BUILDFOLDER=rokku-dev-apache-ranger-postgres
  global:
  - secure: "N/+LQNdznsRHajk4YOtoefuONfHekyao8jwf6wy/p4KhUW1K4kDe25M1RqxtHAIvFYaXQmZKM95CyOXOspSpyKLo3Duobt/fsKXlciHMSda8R0k1OnBq2js7jeLVdbSSblumw/CeOoKLrrIYRhhcwJGexS450VyKn+mH8Z0nraCw8/uShcyYppzSujKvLkNiMS0/VUoIQ/CEuxKDuhcuzQ4ZnXkAt6cRPsZ8qG3B7tcSEhrcoYPGxsEZ9UIlV1uspx5IZUYLoSpaWiM1TA9cjp/LuE8iPZmYad869Ys6OOa9io76Q67d2uqQlJWmBdylH0qGWjKEOr+MsdoB64MqpWTCQzmJi/vi60B9JNLzMXgf9f9/l1mRCekjjz9kXeNH17TAp5nRC7g/ieVFjMPVCAxBDmq3MUjE/qdOc/iOsatSB36sEiecFd4Q9pKqR2PEpUuG08I14iNLrYph7uRqeT3R0p5synLZ/VCsnInIKB0MZlg3uxACQYmy7CLFVNdBa6uLGCw88JO1UCnJrhY6RJjgFEjPm1fc2xqKJeAcg4431PTbxCLSztQZqZh4l8Nu9XB9TKbPNCIhP9zgqz+2+2bdQisEd9wLxomHtCix+Upi0NWSdf2JR6c4cBy6cA6FcNRdFvcDuqTXYCvpO5VAullEiCUzyNyftUgDQs9P3Z8="
  - secure: "CYWZgCgxXjFP77UXwIypxFotrvo47/cgcnstN4bHQL6Inn63lH3jGuAfwWDeVQw1WLjQnQmPuMenPA4lTcMefwbJ81LD4LAb59TcnfoeO+WproyYVV7iBjRCZu6YvonvP3ds84hFbTUrRKCL5NphDejuJiOBl8ArOsM1stQgdNuE9VZCI6tUPHVkNideFjvSCnWvb7t5tg1s0xbqenSL6cZJPqHnzLoWf+jUCVdVjymIzv4wtujLwOlfBDV8Qa2mbFs9SCdt6XCM2de1u5qVnGfSafq5ZxnocF6AmSdo/kihwVmFh8Efvov/sbQp0w7G9pp/l3D2MT5fHPe67yJIbr7nya0Jnj2ukBSC3oY4gVjQCLzjsSMM6tcqDk+PsNyZECPINoCa3racSj1vSsTFOl9AC2O66mZ8OR0qfcvgT64VWDAjct7rjWUsJbv0XmpKs5b4y2sBlHx6GRPWt3wFexQQo3+hhqbEqwN8qFFDjmOA+xG9V9WKCy4/enX2V2lfuIto2k6zGByNZOOhBaY7jq6WH6E6L472SeqmGVnj05kbjv7ZEBASAUwQeftuHoHQ2IgVn+1S8S/TbOSd4+Vau+/2SVDMO9BLx1M95owKvV3mofDiHFzDFmvWBNYBhiyeI9s2S/M7EYZ4r2QUuXZmzX2aVi7HRBHxcjuznGE0OYI="

# We will not build an image on the master tag, thereby forcing people to use tagged versions only
# Also there is an issue with using TRAVIS_BRANCH for PRs since this variable will be set to the target of the PR (e.g. master for PR to master) and then build an image for master unwanted before the merge happened
script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- cd $BUILDFOLDER
- export DOCKER_TAG="${TRAVIS_BRANCH/\//_}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [ "${TRAVIS_BRANCH}" != "master" ]; then 
    echo "Build image for tag ${DOCKER_TAG}";
    docker pull wbaa/$BUILDFOLDER:latest;
    travis_wait 60 docker build --quiet -t wbaa/$BUILDFOLDER:$DOCKER_TAG .;
    docker push wbaa/$BUILDFOLDER:$DOCKER_TAG;
  fi
- if [ -n "$TRAVIS_TAG" ]; then 
    docker tag wbaa/$BUILDFOLDER:$DOCKER_TAG wbaa/$BUILDFOLDER:latest;
    docker push wbaa/$BUILDFOLDER:latest;
  fi
